version: '3.9'

services:

  rabbitmq:
    image: "rabbitmq:3.8.6-management"
    container_name: rabbitmq-broker
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./myrabbit.config:/etc/rabbitmq/rabbitmq.config

